In [1]:

import os
from glob import glob
#

In [26]:
scan_id = "2026-02-bangladesh-bogura"
spatial_data = glob(os.path.join('mnt', scan_id, '02-process-output', 'spatial', '*'))
spatial_data.sort()

spatial_data = [os.path.basename(f) for f in spatial_data]

In [25]:
import yaml
source = os.path.join('frontend', 'source', 'layers.yml',)


with open(source) as f:
      layers = yaml.safe_load(f)


layers['population']

{'fuzzy_string': 'population.*.tif$',
 'title': 'Population density',
 'subtitle': 'Number of persons per 10,000 m<sup>2</sup>',
 'palette': ['#ECEB72', '#8E3933'],
 'basemap': 'satellite',
 'group_id': 'Population density',
 'bins': 5,
 'caption': 'Map data from WorldPop.'}

In [27]:
import re

rows = []
for key, val in layers.items():
    pattern = val.get('fuzzy_string')
    if pattern:
        found = any(re.search(pattern, f) for f in spatial_data)
    else:
        found = False
    rows.append({'layer': key, 'pattern': pattern, 'found': found})

In [28]:
import pandas as pd
df = pd.DataFrame(rows)
df.sort_values(by='found')

                layer                      pattern  found
0            template                         None  False
32           burnable               burn-edit.tif$  False
31              roads              edges-edit.gpkg  False
28              slope                   slope.tif$  False
27          elevation               elevation.tif$  False
26  combined_flooding  combined_flooding_2020.tif$  False
25            coastal            coastal_2020.tif$  False
24            pluvial            pluvial_2020.tif$  False
23            fluvial            fluvial_2020.tif$  False
22     infrastructure         infrastructure.gpkg$  False
21           deforest      deforestation-edit.tif$  False
19         vegetation           ndvi_season.*.tif$  False
33         burnt_area       burnt-area-density.tif  False
15      health_points                health-points  False
34            drought           ndmi_season.*.tif$  False
13      school_points                school-points  False
12       school_zones              school-journeys  False
11      intersections    intersection-density.tif$  False
9          impervious                         None  False
8   builtup_projected         built_2030-edit.tif$  False
14       health_zones              health-journeys  False
6         wsf_tracker        wsf-tracker-edit.tif$  False
5                 wsf                wsf-edit.tif$  False
1          population            population.*.tif$   True
2                 rwi        rwi(?=.shp$|.gpkg$|$)   True
30       liquefaction            liquefaction.tif$   True
29         landslides             landslide.*.tif$   True
3   economic_activity           avg_rad_sum.*.tif$   True
7         ghs_builtup         built_over_time.tif$   True
10         land_cover                      lc.tif$   True
20             forest          forest_cover.*.tif$   True
18         summer_lst                summer.*.tif$   True
16              solar                 solar.*.tif$   True
4     economic_change                  linfit.tif$   True
17        air_quality                   air.*.tif$   True

In [29]:
df[df['found'] == False]

                layer                      pattern  found
0            template                         None  False
5                 wsf                wsf-edit.tif$  False
6         wsf_tracker        wsf-tracker-edit.tif$  False
8   builtup_projected         built_2030-edit.tif$  False
9          impervious                         None  False
11      intersections    intersection-density.tif$  False
12       school_zones              school-journeys  False
13      school_points                school-points  False
14       health_zones              health-journeys  False
15      health_points                health-points  False
19         vegetation           ndvi_season.*.tif$  False
21           deforest      deforestation-edit.tif$  False
22     infrastructure         infrastructure.gpkg$  False
23            fluvial            fluvial_2020.tif$  False
24            pluvial            pluvial_2020.tif$  False
25            coastal            coastal_2020.tif$  False
26  combined_flooding  combined_flooding_2020.tif$  False
27          elevation               elevation.tif$  False
28              slope                   slope.tif$  False
31              roads              edges-edit.gpkg  False
32           burnable               burn-edit.tif$  False
33         burnt_area       burnt-area-density.tif  False
34            drought           ndmi_season.*.tif$  False